// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewNote struct {
	Text   string `json:"text"`
	Title  string `json:"title"`
	UserID string `json:"userId"`
}

type Note struct {
	ID    string `json:"id"`
	Text  string `json:"text"`
	Title string `json:"title"`
	User  *User  `json:"user"`
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
